/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One card game entry in the Open Card Game Rules Reference. Every field is written from scratch in the project's own words; no text is copied or closely paraphrased from any source.
 */
export interface CardGame {
  /**
   * Slug identifying the game. Must match the filename (games/<id>.json).
   */
  id: string;
  /**
   * Display name of the game.
   */
  name: string;
  /**
   * Other names the game is commonly known by. May be empty.
   */
  aliases: string[];
  /**
   * Primary family the game belongs to, chosen by its core mechanic.
   */
  category: "trick-taking" | "shedding" | "rummy-type" | "solitaire" | "casino" | "matching-collecting" | "bluffing";
  players: {
    min: number;
    max: number;
    /**
     * Single best player count. Ranges belong in the prose, not here.
     */
    ideal: number;
  };
  /**
   * What you need to deal, in plain English, e.g. "1 standard deck (52 cards)" or "2 standard decks plus 4 jokers (108 cards)". Written for a person to read; the machine-readable version is in "equipment".
   */
  decks: string;
  /**
   * The same requirement as "decks", but as data, so an app can answer "what can I play with what I own?" without parsing prose.
   */
  equipment: {
    /**
     * How many ordinary 52-card decks you must OWN to play at the minimum player count. Games needing a stripped deck still count the packs they are built from: Euchre is 1, Pinochle is 2.
     */
    standard_decks: number;
    /**
     * How many jokers the game requires. 0 when jokers are unused or optional.
     */
    jokers: number;
    /**
     * Set when play uses a stripped or purpose-built pack rather than a full one, e.g. "24-card euchre deck". Null for ordinary play.
     */
    special_deck: string | null;
    /**
     * True when higher player counts call for shuffling in another deck.
     */
    extra_deck_for_large_groups: boolean;
    /**
     * Anything needed beyond cards, e.g. a cribbage board. Usually empty.
     *
     * @maxItems 4
     */
    other: string[];
  };
  /**
   * How the table starts: deal, layout, dealer selection, anything built before the first turn.
   */
  setup: string;
  /**
   * How a turn works and how the hand proceeds: turn order, legal moves, restrictions, how the hand ends.
   */
  play: string;
  /**
   * What winning looks like and how points (if any) are counted.
   */
  goal_and_scoring: string;
  /**
   * A few well-known variations. Not intended to be exhaustive.
   *
   * @minItems 2
   * @maxItems 8
   */
  variants: [
    {
      name: string;
      description: string;
    },
    {
      name: string;
      description: string;
    },
    ...{
      name: string;
      description: string;
    }[]
  ];
  /**
   * How much there is to learn before a first game, not how hard it is to play well.
   */
  difficulty: "simple" | "easy" | "medium" | "complex";
  /**
   * Rough playing time as a range, e.g. "15-30", or an open-ended floor, e.g. "60+".
   */
  duration_minutes: string;
  /**
   * Facets for filtering. Drawn from a controlled vocabulary so search stays consistent across the collection.
   *
   * @minItems 1
   * @maxItems 10
   */
  tags: [
    (
      | "family-friendly"
      | "kids"
      | "party"
      | "partnership"
      | "solo"
      | "two-player"
      | "large-group"
      | "quick"
      | "long-game"
      | "bluffing"
      | "memory"
      | "strategy"
      | "luck"
      | "speed"
      | "reflex"
      | "counting"
      | "betting"
      | "beginner-friendly"
      | "classic"
      | "travel"
      | "no-table-needed"
    ),
    ...(
      | "family-friendly"
      | "kids"
      | "party"
      | "partnership"
      | "solo"
      | "two-player"
      | "large-group"
      | "quick"
      | "long-game"
      | "bluffing"
      | "memory"
      | "strategy"
      | "luck"
      | "speed"
      | "reflex"
      | "counting"
      | "betting"
      | "beginner-friendly"
      | "classic"
      | "travel"
      | "no-table-needed"
    )[]
  ];
  /**
   * Names of sources checked while verifying the rules. Attribution as good practice; the write-up itself is original.
   *
   * @minItems 1
   * @maxItems 12
   */
  sources_consulted: [string, ...string[]];
}
