#!/usr/bin/env python3
"""Generate rendered/ Markdown from the JSON entries in games/.

Everything under rendered/ is generated output: edit the JSON, then re-run this.
Hand edits to rendered/ will be overwritten.

    python3 scripts/render_markdown.py           # write rendered/
    python3 scripts/render_markdown.py --check   # fail if rendered/ is stale (CI gate)
"""

from __future__ import annotations

import argparse
import sys

from gamelib import (
    RENDERED_DIR,
    SECTIONS,
    category_label,
    facts,
    games_by_category,
    load_games,
)

BANNER = (
    "<!-- Generated by scripts/render_markdown.py from {source}. "
    "Do not edit by hand. -->"
)


def render_game(game: dict) -> str:
    lines = [BANNER.format(source=f"games/{game['id']}.json"), ""]
    lines.append(f"# {game['name']}")
    lines.append("")

    for label, value in facts(game):
        lines.append(f"**{label}:** {value}  ")
    lines.append("")

    for key, heading in SECTIONS:
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(game[key])
        lines.append("")

    lines.append("## Variants")
    lines.append("")
    for variant in game["variants"]:
        lines.append(f"**{variant['name']}** — {variant['description']}")
        lines.append("")

    if game.get("tags"):
        lines.append(f"**Tags:** {', '.join(sorted(game['tags']))}")
        lines.append("")

    lines.append(
        "*Rules verified against: "
        + ", ".join(game["sources_consulted"])
        + ". This write-up is original text, not reproduced from those sources.*"
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "Part of the [Open Card Game Rules Reference](../README.md). "
        "Text licensed [CC BY-SA 4.0](../LICENSE)."
    )
    lines.append("")
    return "\n".join(lines)


def render_index(games: list[dict]) -> str:
    lines = [BANNER.format(source="games/*.json"), ""]
    lines.append("# Card Game Rules — Index")
    lines.append("")
    lines.append(
        f"{len(games)} games, written from scratch and free to reuse under CC BY-SA 4.0."
    )
    lines.append("")

    for category, entries in games_by_category(games):
        lines.append(f"## {category_label(category)}")
        lines.append("")
        lines.append("| Game | Players | Deck | Time | Difficulty |")
        lines.append("| --- | --- | --- | --- | --- |")
        for game in entries:
            row = dict(facts(game))
            lines.append(
                f"| [{game['name']}]({game['id']}.md) "
                f"| {row['Players']} | {row['Deck']} | {row['Time']} "
                f"| {row['Difficulty']} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the rendered output is out of date",
    )
    args = parser.parse_args()

    games = load_games()
    if not games:
        sys.exit("No games found. Nothing to render.")

    wanted = {f"{game['id']}.md": render_game(game) for game in games}
    wanted["index.md"] = render_index(games)

    RENDERED_DIR.mkdir(exist_ok=True)

    if args.check:
        stale = []
        for name, content in sorted(wanted.items()):
            path = RENDERED_DIR / name
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        orphans = [
            p.name for p in RENDERED_DIR.glob("*.md") if p.name not in wanted
        ]
        if stale or orphans:
            for name in stale:
                print(f"stale: rendered/{name}")
            for name in orphans:
                print(f"orphaned: rendered/{name} has no matching game entry")
            print("\nRun: python3 scripts/render_markdown.py")
            return 1
        print(f"rendered/ is up to date ({len(wanted)} files).")
        return 0

    for name, content in sorted(wanted.items()):
        (RENDERED_DIR / name).write_text(content, encoding="utf-8")

    for path in RENDERED_DIR.glob("*.md"):
        if path.name not in wanted:
            path.unlink()
            print(f"removed stale rendered/{path.name}")

    print(f"Wrote {len(wanted)} files to rendered/ ({len(games)} games + index).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
