/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One card game entry in Naibi. Every field is written from scratch in the project's own words; no text is copied or closely paraphrased from any source.
 */
export interface CardGame {
  /**
   * Slug identifying the game. Must match the filename (games/<id>.json).
   */
  id: string;
  /**
   * Display name of the game.
   */
  name: string;
  /**
   * Other names the game is commonly known by. May be empty.
   */
  aliases: string[];
  /**
   * Primary family the game belongs to, chosen by its core mechanic.
   */
  category: "trick-taking" | "shedding" | "rummy-type" | "solitaire" | "casino" | "matching-collecting" | "bluffing";
  players: {
    min: number;
    max: number;
    /**
     * Single best player count. Ranges belong in the prose, not here.
     */
    ideal: number;
  };
  /**
   * What you need to deal, in plain English, e.g. "1 standard deck (52 cards)" or "2 standard decks plus 4 jokers (108 cards)". Written for a person to read; the machine-readable version is in "equipment".
   */
  decks: string;
  /**
   * The same requirement as "decks", but as data, so an app can answer "what can I play with what I own?" without parsing prose.
   */
  equipment: {
    /**
     * How many ordinary 52-card decks you must OWN to play at the minimum player count. Games needing a stripped deck still count the packs they are built from: Euchre is 1, Pinochle is 2. Use 0 for a game that needs a purpose-built pack you cannot make from ordinary cards, such as hanafuda, and name it in special_deck.
     */
    standard_decks: number;
    /**
     * How many jokers the game requires. 0 when jokers are unused or optional.
     */
    jokers: number;
    /**
     * Set when play uses a stripped or purpose-built pack rather than a full one, e.g. "24-card euchre deck". Null for ordinary play.
     */
    special_deck: string | null;
    /**
     * True when higher player counts call for shuffling in another deck.
     */
    extra_deck_for_large_groups: boolean;
    /**
     * Anything needed beyond cards, e.g. a cribbage board. Usually empty.
     *
     * @maxItems 4
     */
    other: string[];
  };
  /**
   * How the table starts: deal, layout, dealer selection, anything built before the first turn.
   */
  setup: string;
  /**
   * The starting table as data, so a setup diagram can be drawn rather than illustrated by hand. Optional: include it where the arrangement is worth seeing, omit it where 'everyone holds cards' says everything (most pure trick-taking games). Rows are drawn top to bottom and each row is centred, which is what makes a pyramid a pyramid and a cross a cross.
   */
  layout?: {
    /**
     * One line under the diagram, for anything the shapes cannot say.
     */
    caption?: string;
    /**
     * How many rows from the top are drawn overlapping one another, for layouts where a card is physically covered by the cards below it — a pyramid, or TriPeaks. Leave unset (0) and every row is drawn clear of its neighbours, which is right for a grid or a clock face. Set it where the covering IS the rule, because a diagram that draws those cards apart contradicts the rule it is illustrating.
     */
    overlapping_rows?: number;
    /**
     * @minItems 1
     * @maxItems 8
     */
    rows: [
      [
        {
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        },
        ...{
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        }[]
      ],
      ...[
        {
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        },
        ...{
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        }[]
      ][]
    ];
  };
  /**
   * How a turn works and how the hand proceeds: turn order, legal moves, restrictions, how the hand ends.
   */
  play: string;
  /**
   * Captioned rows of named cards, for the things prose explains badly: what order cards rank in, and what a valid combination actually looks like. Optional, and worth including only where the answer is not obvious -- a ranking strip for a game that ranks ace high teaches nothing.
   *
   * @minItems 1
   * @maxItems 4
   */
  figures?: [
    {
      /**
       * "ranking" for cards in order of power, "meld" for a valid (or invalid) combination.
       */
      kind: "ranking" | "meld";
      /**
       * What the figure shows, e.g. "Trump ranking when diamonds are trump".
       */
      caption: string;
      /**
       * @minItems 1
       * @maxItems 4
       */
      rows: [
        {
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        },
        ...{
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        }[]
      ];
    },
    ...{
      /**
       * "ranking" for cards in order of power, "meld" for a valid (or invalid) combination.
       */
      kind: "ranking" | "meld";
      /**
       * What the figure shows, e.g. "Trump ranking when diamonds are trump".
       */
      caption: string;
      /**
       * @minItems 1
       * @maxItems 4
       */
      rows: [
        {
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        },
        ...{
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        }[]
      ];
    }[]
  ];
  /**
   * What winning looks like and how points (if any) are counted.
   */
  goal_and_scoring: string;
  /**
   * Hand size by player count, and anything taken out of the deck to make it come out even. Include it where this actually varies -- Hearts strips cards at 3, 5 and 6 players -- and omit it where one number covers every case, since "thirteen each" needs no table.
   *
   * @minItems 1
   * @maxItems 10
   */
  deal?: [
    {
      /**
       * The player count this row applies to.
       */
      players: number;
      /**
       * Cards dealt to each player. Use 0 where the whole deck is shared out and the count follows from the deck size.
       */
      hand: number;
      /**
       * Cards taken out of the deck at this player count, e.g. "2♦". Omit when none are.
       */
      removed?: string;
      /**
       * Anything else specific to this count.
       */
      note?: string;
    },
    ...{
      /**
       * The player count this row applies to.
       */
      players: number;
      /**
       * Cards dealt to each player. Use 0 where the whole deck is shared out and the count follows from the deck size.
       */
      hand: number;
      /**
       * Cards taken out of the deck at this player count, e.g. "2♦". Omit when none are.
       */
      removed?: string;
      /**
       * Anything else specific to this count.
       */
      note?: string;
    }[]
  ];
  /**
   * Point values as a lookup, for games where scoring is something you consult mid-hand rather than remember: Cribbage's combinations, Canasta's card values, Pinochle's melds. The prose in goal_and_scoring still explains how scoring works; this is only the numbers.
   *
   * @minItems 2
   * @maxItems 24
   */
  scoring_table?: [
    {
      /**
       * What scores, e.g. "Fifteen" or "Each ace".
       */
      item: string;
      /**
       * What it is worth, as text so ranges and conditions fit: "2", "-10", "20 each".
       */
      value: string;
      /**
       * A short qualifier, e.g. "only if it takes a trick".
       */
      note?: string;
    },
    {
      /**
       * What scores, e.g. "Fifteen" or "Each ace".
       */
      item: string;
      /**
       * What it is worth, as text so ranges and conditions fit: "2", "-10", "20 each".
       */
      value: string;
      /**
       * A short qualifier, e.g. "only if it takes a trick".
       */
      note?: string;
    },
    ...{
      /**
       * What scores, e.g. "Fifteen" or "Each ace".
       */
      item: string;
      /**
       * What it is worth, as text so ranges and conditions fit: "2", "-10", "20 each".
       */
      value: string;
      /**
       * A short qualifier, e.g. "only if it takes a trick".
       */
      note?: string;
    }[]
  ];
  /**
   * A few well-known variations. Not intended to be exhaustive.
   *
   * @minItems 2
   * @maxItems 8
   */
  variants: [
    {
      name: string;
      description: string;
    },
    {
      name: string;
      description: string;
    },
    ...{
      name: string;
      description: string;
    }[]
  ];
  /**
   * How much there is to learn before a first game, not how hard it is to play well.
   */
  difficulty: "simple" | "easy" | "medium" | "complex";
  /**
   * Rough playing time as a range, e.g. "15-30", or an open-ended floor, e.g. "60+".
   */
  duration_minutes: string;
  /**
   * Facets for filtering. Drawn from a controlled vocabulary so search stays consistent across the collection.
   *
   * @minItems 1
   * @maxItems 10
   */
  tags: [
    (
      | "family-friendly"
      | "kids"
      | "party"
      | "partnership"
      | "solo"
      | "two-player"
      | "large-group"
      | "quick"
      | "long-game"
      | "bluffing"
      | "memory"
      | "strategy"
      | "luck"
      | "speed"
      | "reflex"
      | "counting"
      | "betting"
      | "beginner-friendly"
      | "classic"
      | "travel"
      | "no-table-needed"
    ),
    ...(
      | "family-friendly"
      | "kids"
      | "party"
      | "partnership"
      | "solo"
      | "two-player"
      | "large-group"
      | "quick"
      | "long-game"
      | "bluffing"
      | "memory"
      | "strategy"
      | "luck"
      | "speed"
      | "reflex"
      | "counting"
      | "betting"
      | "beginner-friendly"
      | "classic"
      | "travel"
      | "no-table-needed"
    )[]
  ];
  /**
   * Names of sources checked while verifying the rules. Attribution as good practice; the write-up itself is original.
   *
   * @minItems 1
   * @maxItems 12
   */
  sources_consulted: [string, ...string[]];
}
